
struct xfdf_form_translation ca540_2014[] = {
	{"HOH", USE_KEY_IN_FORM, "128", ""},
	{"MFJ", USE_KEY_IN_FORM, "128", ""},
	{"MFS", USE_KEY_IN_FORM, "128", ""},
	{"QW", USE_KEY_IN_FORM, "128", ""},
	{"Single", USE_KEY_IN_FORM, "128", ""},

	
	{"7m", DOLLAR_ONLY, "131", ""},
	{"7", DOLLAR_ONLY, "132", ""},
	{"8m", DOLLAR_ONLY, "133", ""},
	{"8", DOLLAR_ONLY, "134", ""},
	{"9m", DOLLAR_ONLY, "135", ""},
	{"9", DOLLAR_ONLY, "136", ""},
	{"10m", DOLLAR_ONLY, "149", ""},
	{"10", DOLLAR_ONLY, "150", ""},
	{"11", DOLLAR_ONLY, "151", ""},
	{"12", DOLLAR_ONLY, "201", ""},
	{"13", DOLLAR_ONLY, "202", ""},
	{"14", DOLLAR_ONLY, "203", ""},
	{"15", DOLLAR_ONLY, "204", ""},
	{"16", DOLLAR_ONLY, "205", ""},
	{"17", DOLLAR_ONLY, "206", ""},
	{"18", DOLLAR_ONLY, "207", ""},
	{"19", DOLLAR_ONLY, "208", ""},

	{"3800", USE_KEY_IN_FORM, "209", ""},
	{"3803", USE_KEY_IN_FORM, "209", ""},
	{"TRS", USE_KEY_IN_FORM, "209", ""},
	{"TT", USE_KEY_IN_FORM, "209", ""},

	{"31", DOLLAR_ONLY, "210", ""},
	{"32", DOLLAR_ONLY, "211", ""},
	{"33", DOLLAR_ONLY, "212", ""},

	{"5870a", USE_KEY_IN_FORM, "213", ""},
	{"sg1", USE_KEY_IN_FORM, "213", ""},

	{"34", DOLLAR_ONLY, "214", ""},
	{"35", DOLLAR_ONLY, "215", ""},

	{"40", DOLLAR_ONLY, "216", ""},
	{"43n", DOLLAR_ONLY, "217", ""},
	{"43c", DOLLAR_ONLY, "218", ""},
	{"43", DOLLAR_ONLY, "219", ""},
	{"44n", DOLLAR_ONLY, "220", ""},
	{"44c", DOLLAR_ONLY, "221", ""},
	{"44", DOLLAR_ONLY, "222", ""},
	{"45", DOLLAR_ONLY, "223", ""},
	{"46", DOLLAR_ONLY, "224", ""},
	{"47", DOLLAR_ONLY, "225", ""},
	{"48", DOLLAR_ONLY, "226", ""},

	{"61", DOLLAR_ONLY, "301", ""},
	{"62", DOLLAR_ONLY, "302", ""},
	{"63", DOLLAR_ONLY, "303", ""},
	{"64", DOLLAR_ONLY, "304", ""},
	{"71", DOLLAR_ONLY, "305", ""},
	{"72", DOLLAR_ONLY, "306", ""},
	{"73", DOLLAR_ONLY, "307", ""},
	{"74", DOLLAR_ONLY, "308", ""},
	{"75", DOLLAR_ONLY, "309", ""},
	{"91", DOLLAR_ONLY, "310", ""},
	{"92", DOLLAR_ONLY, "311", ""},
	{"93", DOLLAR_ONLY, "312", ""},
	{"94", DOLLAR_ONLY, "313", ""},
	{"95", DOLLAR_ONLY, "401", ""},

	{NULL, DOLLAR_ONLY, NULL, NULL}
};

struct xfdf_form_translation ca_schedule_540_2014[] = {
	{"7a", DOLLAR_ONLY, "Dollar Amount 1", ""},
	{"7b", DOLLAR_ONLY, "Dollar Amount 2", ""},
	{"7c", DOLLAR_ONLY, "Dollar Amount 3", ""},
	{"8aa", DOLLAR_ONLY, "Dollar Amount 4", ""},
	{"8ab", DOLLAR_ONLY, "Dollar Amount 5", ""},
	{"8ac", DOLLAR_ONLY, "Dollar Amount 6", ""},
	{"9aa", DOLLAR_ONLY, "Dollar Amount 8", ""},
	{"9ab", DOLLAR_ONLY, "Dollar Amount 9", ""},
	{"9ac", DOLLAR_ONLY, "Dollar Amount 10", ""},
	{"10a", DOLLAR_ONLY, "Dollar Amount 11", ""},
	{"10b", DOLLAR_ONLY, "Dollar Amount 12", ""},
	{"11a", DOLLAR_ONLY, "Dollar Amount 13", ""},
	{"12a", DOLLAR_ONLY, "Dollar Amount 15", ""},
	{"12b", DOLLAR_ONLY, "Dollar Amount 16", ""},
	{"12c", DOLLAR_ONLY, "Dollar Amount 17", ""},
	{"13a", DOLLAR_ONLY, "Dollar Amount 18", ""},
	{"13b", DOLLAR_ONLY, "Dollar Amount 19", ""},
	{"13c", DOLLAR_ONLY, "Dollar Amount 20", ""},
	{"14a", DOLLAR_ONLY, "Dollar Amount 21", ""},
	{"14b", DOLLAR_ONLY, "Dollar Amount 22", ""},
	{"14c", DOLLAR_ONLY, "Dollar Amount 23", ""},
	{"15ba", DOLLAR_ONLY, "Dollar Amount 25", ""},
	{"15bb", DOLLAR_ONLY, "Dollar Amount 26", ""},
	{"15bc", DOLLAR_ONLY, "Dollar Amount 27", ""},
	{"16ba", DOLLAR_ONLY, "Dollar Amount 29", ""},
	{"16bb", DOLLAR_ONLY, "Dollar Amount 30", ""},
	{"16bc", DOLLAR_ONLY, "Dollar Amount 31", ""},
	{"17a", DOLLAR_ONLY, "Dollar Amount 32", ""},
	{"17b", DOLLAR_ONLY, "Dollar Amount 33", ""},
	{"17c", DOLLAR_ONLY, "Dollar Amount 34", ""},
	{"18a", DOLLAR_ONLY, "Dollar Amount 35", ""},
	{"18b", DOLLAR_ONLY, "Dollar Amount 36", ""},
	{"18c", DOLLAR_ONLY, "Dollar Amount 37", ""},
	{"19a", DOLLAR_ONLY, "Dollar Amount 38", ""},
	{"19b", DOLLAR_ONLY, "Dollar Amount 39", ""},
	{"20a", DOLLAR_ONLY, "Dollar Amount 40", ""},
	{"20ba", DOLLAR_ONLY, "Dollar Amount 41", ""},
	{"20bb", DOLLAR_ONLY, "Dollar Amount 42", ""},

	{"21a", DOLLAR_ONLY, "Dollar Amount 42b", ""},
	{"21ba", DOLLAR_ONLY, "Dollar Amount 43", ""},
	{"21bb", DOLLAR_ONLY, "Dollar Amount 44", ""},
	{"21cc", DOLLAR_ONLY, "Dollar Amount 45", ""},
	{"21bd", DOLLAR_ONLY, "Dollar Amount 46", ""},
	{"21be", DOLLAR_ONLY, "Dollar Amount 47", ""},
	{"21bf", DOLLAR_ONLY, "Dollar Amount 48", ""},
	{"21cf", DOLLAR_ONLY, "Dollar Amount 49", ""},
	{"22a", DOLLAR_ONLY, "Dollar Amount 50", ""},
	{"22b", DOLLAR_ONLY, "Dollar Amount 51", ""},
	{"22c", DOLLAR_ONLY, "Dollar Amount 52", ""},
	{"23a", DOLLAR_ONLY, "Dollar Amount 53", ""},
	{"23b", DOLLAR_ONLY, "Dollar Amount 54", ""},
	{"24a", DOLLAR_ONLY, "Dollar Amount 55", ""},
	{"24b", DOLLAR_ONLY, "Dollar Amount 56", ""},
	{"24c", DOLLAR_ONLY, "Dollar Amount 57", ""},
	{"25a", DOLLAR_ONLY, "Dollar Amount 58", ""},
	{"25b", DOLLAR_ONLY, "Dollar Amount 59", ""},
	{"26a", DOLLAR_ONLY, "Dollar Amount 60", ""},
	{"27a", DOLLAR_ONLY, "Dollar Amount 61a", ""},
	{"28a", DOLLAR_ONLY, "Dollar Amount 62", ""},
	{"29a", DOLLAR_ONLY, "Dollar Amount 63", ""},
	{"30a", DOLLAR_ONLY, "Dollar Amount 64", ""},
	{"31aa", DOLLAR_ONLY, "Dollar Amount 65", ""},
	{"31ac", DOLLAR_ONLY, "Dollar Amount 66", ""},
	{"32a", DOLLAR_ONLY, "Dollar Amount 67", ""},
	{"33a", DOLLAR_ONLY, "Dollar Amount 69", ""},
	{"33c", DOLLAR_ONLY, "Dollar Amount 70", ""},
	{"34a", DOLLAR_ONLY, "Dollar Amount 71", ""},
	{"34b", DOLLAR_ONLY, "Dollar Amount 72", ""},
	{"35a", DOLLAR_ONLY, "Dollar Amount 73", ""},
	{"35b", DOLLAR_ONLY, "Dollar Amount 74", ""},
	{"36a", DOLLAR_ONLY, "Dollar Amount 75", ""},
	{"36b", DOLLAR_ONLY, "Dollar Amount 76", ""},
	{"36c", DOLLAR_ONLY, "Dollar Amount 77", ""},
	{"37a", DOLLAR_ONLY, "Dollar Amount 78", ""},
	{"37b", DOLLAR_ONLY, "Dollar Amount 79", ""},
	{"37c", DOLLAR_ONLY, "Dollar Amount 80", ""},
	{"38", DOLLAR_ONLY, "Dollar Amount 82a", ""},
	{"39", DOLLAR_ONLY, "Dollar Amount 82b", ""},
	{"40", DOLLAR_ONLY, "Dollar Amount 83", ""},
	{"41", DOLLAR_ONLY, "Dollar Amount 84", ""},
	{"42", DOLLAR_ONLY, "Dollar Amount 85", ""},
	{"43", DOLLAR_ONLY, "Dollar Amount 86", ""},
	{"44", DOLLAR_ONLY, "Dollar Amount 87", ""},

	{NULL, DOLLAR_ONLY, NULL, NULL}
};
