
struct xfdf_form_translation it201_2014[] = {
	{"Single", IF_SET, "Filing Status", "Single"},
	{"MFJ", IF_SET, "Filing Status", "2 Married Filing Joint Return (enter spouse&#144;s social security number above)"},
	{"MFS", IF_SET, "Filing Status", "3 Married Filing Seperate Return (enter spouse&#144;s social security number above)"},
	{"HOH", IF_SET, "Filing Status", "Head of Household (with qualifying person)"},
	{"QW", IF_SET, "Filing Status", "Qualifying widow(er) with dependent child"},
	{"itemized", IF_SET, "Itemized", "yes"},
	{"did_not_itemize", IF_SET, "Itemized", "no"},
	{"dependent", IF_SET, "Dependent", "yes"},
	{"not_dependent", IF_SET, "Dependent", "no"},
	
	{"ny_itemized", IF_SET, "Deduction", "Itemized"},
	{"ny_standard", IF_SET, "Deduction", "Standard"},

	{"1", DOLLAR_ONLY, "nys 1 dollars", ""},
	{"2", DOLLAR_ONLY, "nys 2 dollars", ""},
	{"3", DOLLAR_ONLY, "nys 3 dollars", ""},
	{"4", DOLLAR_ONLY, "nys 4 dollars", ""},
	{"5", DOLLAR_ONLY, "nys 5 dollars", ""},
	{"6", DOLLAR_ONLY, "nys 6 dollars", ""},
	{"7", DOLLAR_ONLY, "nys 7 dollars", ""},
	{"8", DOLLAR_ONLY, "nys 8 dollars", ""},
	{"9", DOLLAR_ONLY, "nys 9 dollars", ""},
	{"10", DOLLAR_ONLY, "nys 10 dollars", ""},
	{"11", DOLLAR_ONLY, "nys 11 dollars", ""},
	{"12", DOLLAR_ONLY, "nys 12 dollars", ""},
	{"13", DOLLAR_ONLY, "nys 13 dollars", ""},
	{"14", DOLLAR_ONLY, "nys 14 dollars", ""},
	{"15", DOLLAR_ONLY, "nys 15 dollars", ""},
	{"16", DOLLAR_ONLY, "nys 16 dollars", ""},
	{"17", DOLLAR_ONLY, "nys 17 dollars", ""},
	{"18", DOLLAR_ONLY, "nys 18 dollars", ""},
	{"19", DOLLAR_ONLY, "nys 19 dollars", ""},
	{"20", DOLLAR_ONLY, "nys 20 dollars", ""},
	{"21", DOLLAR_ONLY, "nys 21 dollars", ""},
	{"22", DOLLAR_ONLY, "nys 22 dollars", ""},
	{"23", DOLLAR_ONLY, "nys 23 dollars", ""},
	{"24", DOLLAR_ONLY, "nys 24 dollars", ""},
	{"25", DOLLAR_ONLY, "nys 25 dollars", ""},
	{"26", DOLLAR_ONLY, "nys 26 dollars", ""},
	{"27", DOLLAR_ONLY, "nys 27 dollars", ""},
	{"28", DOLLAR_ONLY, "nys 28 dollars", ""},
	{"29", DOLLAR_ONLY, "nys 29 dollars", ""},
	{"30", DOLLAR_ONLY, "nys 30 dollars", ""},
	{"31", DOLLAR_ONLY, "nys 31 dollars", ""},
	{"32", DOLLAR_ONLY, "nys 32 dollars", ""},
	{"33", DOLLAR_ONLY, "nys 33 dollars", ""},
	{"34", DOLLAR_ONLY, "34 dollars", ""},
	{"35", DOLLAR_ONLY, "35 dollars", ""},
	{"36", DOLLAR_ONLY, "36 dollars", ""},
	{"37", DOLLAR_ONLY, "37 dollars", ""},
	{"38", DOLLAR_ONLY, "38 dollars", ""},
	{"39", DOLLAR_ONLY, "39 dollars", ""},
	{"40", DOLLAR_ONLY, "40 dollars", ""},
	{"41", DOLLAR_ONLY, "41 dollars", ""},
	{"42", DOLLAR_ONLY, "42 dollars", ""},
	{"43", DOLLAR_ONLY, "43 dollars", ""},
	{"44", DOLLAR_ONLY, "44 dollars", ""},
	{"45", DOLLAR_ONLY, "45 dollars", ""},
	{"46", DOLLAR_ONLY, "46 dollars", ""},
	{"47", DOLLAR_ONLY, "47 dollars", ""},
	{"48", DOLLAR_ONLY, "48 dollars", ""},
	{"49", DOLLAR_ONLY, "49 dollars", ""},
	{"50", DOLLAR_ONLY, "50 dollars", ""},
	{"51", DOLLAR_ONLY, "51 dollars", ""},
	{"52", DOLLAR_ONLY, "52 dollars", ""},
	{"53", DOLLAR_ONLY, "53 dollars", ""},
	{"54", DOLLAR_ONLY, "54 dollars", ""},
	{"55", DOLLAR_ONLY, "55 dollars", ""},
	{"56", DOLLAR_ONLY, "56 dollars", ""},
	{"57", DOLLAR_ONLY, "57 dollars", ""},
	{"58", DOLLAR_ONLY, "58 dollars", ""},
	{"59", DOLLAR_ONLY, "59 dollars", ""},
	{"60", DOLLAR_ONLY, "60 dollars", ""},
	{"61", DOLLAR_ONLY, "61 dollars", ""},
	{"62", DOLLAR_ONLY, "62 dollars", ""},
	{"63", DOLLAR_ONLY, "63 dollars", ""},
	{"64", DOLLAR_ONLY, "64 dollars", ""},
	{"65", DOLLAR_ONLY, "65 dollars", ""},
	{"66", DOLLAR_ONLY, "66 dollars", ""},
	{"67", DOLLAR_ONLY, "67 dollars", ""},
	{"68", DOLLAR_ONLY, "68 dollars", ""},
	{"69", DOLLAR_ONLY, "69 dollars", ""},
	{"70", DOLLAR_ONLY, "70 dollars", ""},
	{"71", DOLLAR_ONLY, "71 dollars", ""},
	{"72", DOLLAR_ONLY, "72 dollars", ""},
	{"73", DOLLAR_ONLY, "73 dollars", ""},
	{"74", DOLLAR_ONLY, "74 dollars", ""},
	{"75", DOLLAR_ONLY, "75 dollars", ""},
	{"76", DOLLAR_ONLY, "76 dollars", ""},
	{"77", DOLLAR_ONLY, "77 dollars", ""},
	{"78", DOLLAR_ONLY, "78 dollars", ""},
	{"79", DOLLAR_ONLY, "79 dollars", ""},
	{"80", DOLLAR_ONLY, "80 dollars", ""},
	{"81", DOLLAR_ONLY, "81 dollars", ""},
	{"82", DOLLAR_ONLY, "82 dollars", ""},

	{NULL, DOLLAR_ONLY, NULL, NULL}
};

struct xfdf_form_translation it201d_2014[] = {
	{"1", DOLLAR_ONLY, "dollars.0", ""},
	{"2", DOLLAR_ONLY, "dollars.1", ""},
	{"3", DOLLAR_ONLY, "dollars.2", ""},
	{"4", DOLLAR_ONLY, "dollars.3", ""},
	{"5", DOLLAR_ONLY, "dollars.4", ""},
	{"6", DOLLAR_ONLY, "dollars.5", ""},
	{"7", DOLLAR_ONLY, "dollars.6", ""},
	{"8", DOLLAR_ONLY, "dollars.7", ""},
	{"9", DOLLAR_ONLY, "dollars.8", ""},
	{"10", DOLLAR_ONLY, "dollars.9", ""},
	{"11", DOLLAR_ONLY, "dollars.10", ""},
	{"12", DOLLAR_ONLY, "dollars.11", ""},
	{"13", DOLLAR_ONLY, "dollars.12", ""},
	{"14", DOLLAR_ONLY, "dollars.13", ""},
	{"15", DOLLAR_ONLY, "dollars.14", ""},
	{"16", DOLLAR_ONLY, "dollars.15", ""},

	{NULL, DOLLAR_ONLY, NULL, NULL}
};
