
struct xfdf_form_translation pa40_2014[] = {
	{"Single", IF_SET, "Filing Status", "1"},
	{"MFJ", IF_SET, "Filing Status", "2"},
	{"MFS", IF_SET, "Filing Status", "3"},
	{"Final", IF_SET, "Filing Status", "4"},
	{"Deceased", IF_SET, "Filing Status", "5"},

	{"1a", DOLLAR_AND_CENTS_ONE, "1a. Gross Compensation", ""},
	{"1b", DOLLAR_AND_CENTS_ONE, "1b. Unreimbursed Employee Business Expenses", ""},
	{"1c", DOLLAR_AND_CENTS_ONE, "1c. Net Compensation", ""},
	{"2", DOLLAR_AND_CENTS_ONE, "2. Interest Income", ""},
	{"3", DOLLAR_AND_CENTS_ONE, "3. Dividend  and Capital Gains Distributions Income", ""},
	{"4l", IF_SET, "4. Loss", "none"},
	{"4", DOLLAR_AND_CENTS_ONE, "4. Net Income or Loss from the Operation of a Business, etc", ""},
	{"5l", IF_SET, "5. Loss", "none"},
	{"5", DOLLAR_AND_CENTS_ONE, "5. Net Gain or Loss from Sale, etc. of Property", ""},
	{"6l", IF_SET, "6. Loss", "none"},
	{"6", DOLLAR_AND_CENTS_ONE, "6. Net Income or Loss from Rents, etc", ""},
	{"7", DOLLAR_AND_CENTS_ONE, "7. Estate or Trust income", ""},
	{"8", DOLLAR_AND_CENTS_ONE, "8. Gambling and Lottery Winnings", ""},
	{"9", DOLLAR_AND_CENTS_ONE, "9. Total PA Taxable Income", ""},
	{"10", DOLLAR_AND_CENTS_ONE, "10.  Other Deductions", ""},
	{"11", DOLLAR_AND_CENTS_ONE, "11. Adjusted PA Taxable Income", ""},
	{"12", DOLLAR_AND_CENTS_ONE, "12. PA Tax Liability. Multiply Line 11 by 3.07%", ""},
	{"13", DOLLAR_AND_CENTS_ONE, "13. Total PA Tax Withheld", ""},
	{"14", DOLLAR_AND_CENTS_ONE, "14. Credit from your PA Income Tax Return", ""},
	{"15", DOLLAR_AND_CENTS_ONE, "15. Estimated Installment Payments", ""},
	{"16", DOLLAR_AND_CENTS_ONE, "16. Extension Payment", ""},
	{"17", DOLLAR_AND_CENTS_ONE, "17. Nonredsident Tax Withheld", ""},
	{"18", DOLLAR_AND_CENTS_ONE, "18.Total Estimated Payments and Credits", ""},
	{"20", DOLLAR_AND_CENTS_ONE, "20. Total Eligibility Income", ""},
	{"21", DOLLAR_AND_CENTS_ONE, "21. Tax Forgiveness Credit", ""},
	{"22", DOLLAR_AND_CENTS_ONE, "22. Resident Credit", ""},
	{"23", DOLLAR_AND_CENTS_ONE, "23.Total Other Credits", ""},
	{"24", DOLLAR_AND_CENTS_ONE, "24. Total Payments and Credits", ""},
	{"25", DOLLAR_AND_CENTS_ONE, "25. USE TAX", ""},
	{"26", DOLLAR_AND_CENTS_ONE, "26. TAX DUE", ""},
	{"27rev", DOLLAR_AND_CENTS_ONE, "27. REV-1630", ""},
	{"27", DOLLAR_AND_CENTS_ONE, "27.Penalties and Interest", ""},
	{"27code", DOLLAR_AND_CENTS_ONE, "27. Code", ""},
	{"28", DOLLAR_AND_CENTS_ONE, "28. TOTAL PAYMENT", ""},
	{"29", DOLLAR_AND_CENTS_ONE, "29. OVERPAYMENT", ""},
	{"30", DOLLAR_AND_CENTS_ONE, "30. Refund", ""},
	{"31", DOLLAR_AND_CENTS_ONE, "31. Credit", ""},

	{NULL, DOLLAR_ONLY, NULL, NULL}
};
